version: "3"

services:

    database:
        image: mysql:8.0.26
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"

    redis:
        image: redis:6.2.4-alpine
        ports:
            - "6379:6379"
