version: "3"

services:

    database:
        image: mysql:8.0.26
        environment:
            MYSQL_DATABASE: "test"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "root1234"
        ports:
            - "3306:3306"

    redis:
        image: redis:6.2.4-alpine
        ports:
            - "6379:6379"
