name: on push to main
on:
  push:
    branches:
      - main

jobs:
  prepare_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        id: cache-build
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache-build.outputs.cache-hit != 'true'

  build_and_deploy_backend:
    needs: prepare_build
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "valor-launchpad-staging"
          heroku_email: "sergey.melnik@valor-software.com"

  build_and_deploy_frontend:
    needs: prepare_build
    runs-on: ubuntu-latest
    steps:
      - run: npm run build:front
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          channelId: live
          projectId: valor-launchpad-3824c

  refresh_database:
    needs: [prepare_build, build_and_deploy_backend]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - run: npm run schema:drop
      - run: npm run schema:sync
      - run: npm run seed:run
